**Python 与 NumPy 向量相加对比**

In [1]:
def pyVector(n):
    x = range(n)
    y = range(n)
    z = []
    for i in range(len(x)):
        x1 = i ** 2
        y1 = i ** 3
        z.append(x1 + y1)
    return z

In [2]:
pyVector(5)

[0, 2, 12, 36, 80]

In [3]:
import numpy as np

In [4]:
def npVector(n):
    x = np.arange(n) ** 2
    y = np.arange(n) ** 3
    z = x + y
    return z

In [5]:
npVector(5)

array([ 0,  2, 12, 36, 80], dtype=int32)

In [7]:
x = np.arange(5) ** 2
x

array([ 0,  1,  4,  9, 16], dtype=int32)

In [9]:
y = np.arange(5) ** 3
y

array([ 0,  1,  8, 27, 64], dtype=int32)

In [10]:
z = x + y
z

array([ 0,  2, 12, 36, 80], dtype=int32)

In [12]:
data = [10,15,17,-20,40]
data

[10, 15, 17, -20, 40]

In [13]:
arr = np.array(data)
arr

array([ 10,  15,  17, -20,  40])

In [14]:
data2 = ((10,21,33,44,55),(66,77,88,99,22))
arr2 = np.array(data2)
arr2

array([[10, 21, 33, 44, 55],
       [66, 77, 88, 99, 22]])

In [15]:
# 选取第一行的所有数据
arr2[0]

array([10, 21, 33, 44, 55])

In [16]:
# 选取某个数据
arr2[0][3]

44

In [17]:
arr2[0,3]

44

In [18]:
arr2[0,3] = 110
arr2

array([[ 10,  21,  33, 110,  55],
       [ 66,  77,  88,  99,  22]])

**创建多维数组及属性**

In [23]:
# dtype表示获取numpy数组的数据类型
arr.dtype

dtype('int32')

In [20]:
arr.ndim,arr2.ndim

(1, 2)

In [21]:
arr2.shape

(2, 5)

In [24]:
type(data)

list

In [25]:
type(arr)

numpy.ndarray

## 创建数组的函数

In [26]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
np.zeros((5,8))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.zeros((3,4,5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [29]:
np.empty((4,5,6))

array([[[  4.18985370e-316,  -1.82150599e+194,   4.16274812e-316,
           9.41275786e-272,   0.00000000e+000,   0.00000000e+000],
        [  4.17718907e-316,   5.48332651e+003,   2.73610472e-316,
          -6.88013862e+160,   0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   4.18744706e-316,  -1.28895493e-051],
        [  2.73537231e-316,  -8.26602403e+007,   0.00000000e+000,
           0.00000000e+000,   3.99741004e-316,   2.31616322e+110],
        [  2.73533635e-316,   1.56943883e+265,   4.19314778e-316,
          -9.54801113e-082,   2.73576006e-316,   2.23358970e+245]],

       [[  2.73605412e-316,   1.82640327e-301,   3.97551622e-316,
           4.66934278e+095,   4.19311933e-316,   1.00404362e-244],
        [  4.18655181e-316,  -1.54464240e+086,   4.18016176e-316,
           3.17218751e-193,   0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   2.17275526e-316,
 

In [30]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
np.arange(1,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
np.linspace(1,10)

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [33]:
np.linspace(1,10,7)

array([  1. ,   2.5,   4. ,   5.5,   7. ,   8.5,  10. ])

In [34]:
np.linspace(1,10,7,endpoint=False)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571])

## numpy数组类型

In [35]:
data3 = [1,2,3,4,5]
arr3 = np.array(data3)

In [39]:
arr3.dtype

dtype('int32')

In [37]:
# astyp方法的作用是显示地转为指定的数据类型(numpy数据类型)
arr_float = arr3.astype(np.float16)
arr_float

array([ 1.,  2.,  3.,  4.,  5.], dtype=float16)

In [40]:
data4 = [3.3,-5.7,4.4,42,55,12,0.44]
arr4 = np.array(data4)
arr4

array([  3.3 ,  -5.7 ,   4.4 ,  42.  ,  55.  ,  12.  ,   0.44])

In [41]:
# 浮点数转换为整数，则小数位将会被截掉
arr4.astype(np.int32)

array([ 3, -5,  4, 42, 55, 12,  0])

In [42]:
data5 = ['3.15','-4.77','21','33.22']
arr_str = np.array(data5)
arr_str

array(['3.15', '-4.77', '21', '33.22'],
      dtype='<U5')

In [43]:
arr_str.astype(np.float)

array([  3.15,  -4.77,  21.  ,  33.22])

** NumPy 模拟商品数据类型**

In [44]:
myType = np.dtype([('name',np.str_,40),('number',np.int32),('price',np.float32)])
print(myType['name'])

<U40


In [46]:
items = np.array([('华硕I7笔记本',20600,999.9),('微星I7笔记本',30070,888.8)],dtype=myType)
items

array([('华硕I7笔记本', 20600,  999.90002441), ('微星I7笔记本', 30070,  888.79998779)],
      dtype=[('name', '<U40'), ('number', '<i4'), ('price', '<f4')])

In [47]:
items[1]

('微星I7笔记本', 30070,  888.79998779)

In [49]:
arr5 = np.array([[1,2,3],[4,5,6]])

In [51]:
arr5 * arr5

array([[ 1,  4,  9],
       [16, 25, 36]])

In [53]:
arr5 - arr5

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
1 / arr5

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [56]:
arr5 ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])