In [2]:
import numpy as np

In [4]:
arr2d = np.arange(1,24,2).reshape(3,4)
arr2d.ndim
arr2d

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [5]:
arr2d[1]

array([ 9, 11, 13, 15])

In [6]:
arr2d[2,3]

23

In [8]:
arr3d = np.arange(1,49).reshape(3,4,4)
arr3d.ndim
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [9]:
arr3d[1]

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
arr3d[1,3]

array([29, 30, 31, 32])

In [11]:
arr3d[2,1,2]

39

**改变数组维度**

In [17]:
# ravel方法多维数组降为一维数组，返回的是视图，所做的修改会影响原始矩阵
arr3d.ravel()

2

In [13]:
# flatten方法多维数组降为一维数组，返回的是拷贝副本，所做的修改不会影响原始矩阵
arr3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [16]:
arr3d.shape = (6,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [18]:
arr3d.transpose()

array([[ 1,  9, 17, 25, 33, 41],
       [ 2, 10, 18, 26, 34, 42],
       [ 3, 11, 19, 27, 35, 43],
       [ 4, 12, 20, 28, 36, 44],
       [ 5, 13, 21, 29, 37, 45],
       [ 6, 14, 22, 30, 38, 46],
       [ 7, 15, 23, 31, 39, 47],
       [ 8, 16, 24, 32, 40, 48]])

In [19]:
arr3d.T

array([[ 1,  9, 17, 25, 33, 41],
       [ 2, 10, 18, 26, 34, 42],
       [ 3, 11, 19, 27, 35, 43],
       [ 4, 12, 20, 28, 36, 44],
       [ 5, 13, 21, 29, 37, 45],
       [ 6, 14, 22, 30, 38, 46],
       [ 7, 15, 23, 31, 39, 47],
       [ 8, 16, 24, 32, 40, 48]])

In [20]:
arr3d

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [22]:
# 返回一个新数组的同时改变原数组本身
arr3d.resize(3,16)
arr3d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

**更多索引**

In [23]:
arr2d

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [24]:
arr2d[:2]

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [25]:
arr2d[:2,1:]

array([[ 3,  5,  7],
       [11, 13, 15]])

In [26]:
arr2d[2,:1]

array([17])

In [27]:
arr2d[:,:1]

array([[ 1],
       [ 9],
       [17]])

In [28]:
arr2d[:,1::2]

array([[ 3,  7],
       [11, 15],
       [19, 23]])

**布尔值索引**

In [31]:
moni_citys = np.array(['BJ','SH','BJ','CQ','SH','CQ','BJ'])
moni_data= np.random.randn(7,8) * 2
moni_data

array([[ 0.09924482, -3.36392043,  3.36911955,  0.55159712, -1.20199767,
        -0.9858985 ,  1.13446556, -4.09359998],
       [ 3.3923564 ,  2.05853163, -0.01877853,  1.15476182, -0.91968719,
         1.28071348, -0.676174  , -2.66002218],
       [ 0.28463351,  0.31494544,  2.38645149, -0.21611226,  1.9996772 ,
         1.73039469,  1.96694662, -0.10446474],
       [-2.66571013,  0.16319533, -2.76253751,  1.33699383,  1.31594978,
        -0.99891241,  1.63294492, -1.12192388],
       [-2.16173157,  0.48048997,  1.29898023,  0.41281623, -1.5464178 ,
        -0.7783117 , -1.82124574,  2.02218546],
       [-4.76248432, -3.67177039,  0.66235077, -1.17487374, -0.01352619,
         0.52704527, -1.1237382 ,  1.41877209],
       [-0.82670234, -0.37746833, -1.69458167,  2.36372287,  3.59096316,
         1.20651518,  1.52828956, -0.61438525]])

In [32]:
moni_citys == 'BJ'

array([ True, False,  True, False, False, False,  True], dtype=bool)

In [33]:
moni_data[moni_citys == 'BJ']

array([[ 0.09924482, -3.36392043,  3.36911955,  0.55159712, -1.20199767,
        -0.9858985 ,  1.13446556, -4.09359998],
       [ 0.28463351,  0.31494544,  2.38645149, -0.21611226,  1.9996772 ,
         1.73039469,  1.96694662, -0.10446474],
       [-0.82670234, -0.37746833, -1.69458167,  2.36372287,  3.59096316,
         1.20651518,  1.52828956, -0.61438525]])

In [34]:
moni_data[moni_citys == 'BJ',2:]

array([[ 3.36911955,  0.55159712, -1.20199767, -0.9858985 ,  1.13446556,
        -4.09359998],
       [ 2.38645149, -0.21611226,  1.9996772 ,  1.73039469,  1.96694662,
        -0.10446474],
       [-1.69458167,  2.36372287,  3.59096316,  1.20651518,  1.52828956,
        -0.61438525]])

In [35]:
moni_data[moni_citys != 'BJ']

array([[ 3.3923564 ,  2.05853163, -0.01877853,  1.15476182, -0.91968719,
         1.28071348, -0.676174  , -2.66002218],
       [-2.66571013,  0.16319533, -2.76253751,  1.33699383,  1.31594978,
        -0.99891241,  1.63294492, -1.12192388],
       [-2.16173157,  0.48048997,  1.29898023,  0.41281623, -1.5464178 ,
        -0.7783117 , -1.82124574,  2.02218546],
       [-4.76248432, -3.67177039,  0.66235077, -1.17487374, -0.01352619,
         0.52704527, -1.1237382 ,  1.41877209]])

In [38]:
more_citys = (moni_citys == 'BJ') | (moni_citys == 'CQ')
more_citys

array([ True, False,  True,  True, False,  True,  True], dtype=bool)

In [39]:
moni_data[more_citys]

array([[ 0.09924482, -3.36392043,  3.36911955,  0.55159712, -1.20199767,
        -0.9858985 ,  1.13446556, -4.09359998],
       [ 0.28463351,  0.31494544,  2.38645149, -0.21611226,  1.9996772 ,
         1.73039469,  1.96694662, -0.10446474],
       [-2.66571013,  0.16319533, -2.76253751,  1.33699383,  1.31594978,
        -0.99891241,  1.63294492, -1.12192388],
       [-4.76248432, -3.67177039,  0.66235077, -1.17487374, -0.01352619,
         0.52704527, -1.1237382 ,  1.41877209],
       [-0.82670234, -0.37746833, -1.69458167,  2.36372287,  3.59096316,
         1.20651518,  1.52828956, -0.61438525]])

In [41]:
moni_data[moni_data < 2.5] = 0
moni_data

array([[ 0.        ,  0.        ,  3.36911955,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 3.3923564 ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.59096316,
         0.        ,  0.        ,  0.        ]])

In [43]:
moni_data[moni_citys != 'BJ'] = 0 
moni_data

array([[ 0.        ,  0.        ,  3.36911955,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.59096316,
         0.        ,  0.        ,  0.        ]])

**花式索引**

In [45]:
arr = np.empty((10,6))
for i in range(10):
    arr[i] = i

arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.]])

In [47]:
# 特定顺序选取子集
arr[[9,1,4,7]]

array([[ 9.,  9.,  9.,  9.,  9.,  9.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.],
       [ 7.,  7.,  7.,  7.,  7.,  7.]])

In [48]:
arr1 = np.arange(1,61).reshape(10,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [49]:
arr1[[9,1,4,7],[3,0,4,2]]

array([58,  7, 29, 45])

In [52]:
arr1[(9,3),(4,1)]

array([59, 20])

In [53]:
arr1[[9,1,4,7]][:,[2,0,5,3,1,4]]

array([[57, 55, 60, 58, 56, 59],
       [ 9,  7, 12, 10,  8, 11],
       [27, 25, 30, 28, 26, 29],
       [45, 43, 48, 46, 44, 47]])

In [55]:
arr1[np.ix_([9,1,4,7],[2,0,5,3,1,4])]

array([[57, 55, 56, 59],
       [ 9,  7,  8, 11],
       [27, 25, 26, 29],
       [45, 43, 44, 47]])

**数组组合**

In [56]:
arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
arr2 = 2 * arr1
arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [60]:
np.hstack((arr1,arr2)) # 或者使用 np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4,  2,  4,  6,  8],
       [ 5,  6,  7,  8, 10, 12, 14, 16],
       [ 9, 10, 11, 12, 18, 20, 22, 24],
       [13, 14, 15, 16, 26, 28, 30, 32]])

In [63]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [64]:
np.dstack((arr1,arr2))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6],
        [ 4,  8]],

       [[ 5, 10],
        [ 6, 12],
        [ 7, 14],
        [ 8, 16]],

       [[ 9, 18],
        [10, 20],
        [11, 22],
        [12, 24]],

       [[13, 26],
        [14, 28],
        [15, 30],
        [16, 32]]])

In [65]:
np.column_stack((arr1,arr2))

array([[ 1,  2,  3,  4,  2,  4,  6,  8],
       [ 5,  6,  7,  8, 10, 12, 14, 16],
       [ 9, 10, 11, 12, 18, 20, 22, 24],
       [13, 14, 15, 16, 26, 28, 30, 32]])

In [66]:
np.row_stack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

**数组分割**

In [68]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
np.hsplit(arr1,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]]), array([[ 4],
        [ 8],
        [12],
        [16]])]

In [69]:
np.split(arr1,4,axis=1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]]), array([[ 4],
        [ 8],
        [12],
        [16]])]

In [70]:
np.vsplit(arr1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [71]:
arr2 = np.arange(1,28).reshape(3,3,3)
np.dsplit(arr2,3)

[array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]]), array([[[ 3],
         [ 6],
         [ 9]],
 
        [[12],
         [15],
         [18]],
 
        [[21],
         [24],
         [27]]])]

**数组属性**

In [72]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [73]:
arr1.size

16

In [74]:
arr1.itemsize

4

In [76]:
arr1.nbytes

64