**线性代数**

In [2]:
import numpy as np

In [4]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [6]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [ ]:
6 + -2 + 24
23 + 14 + 27

**随机数生成**

In [7]:
s = np.random.normal(size=(6,6))
s

array([[-1.15152041, -0.21757914,  0.86545889,  1.54338805,  0.54239125,
        -0.11245197],
       [-0.08694201, -0.20364572, -1.96914278,  1.17545307,  2.05147012,
        -0.153386  ],
       [ 0.69286181, -0.99340047,  0.62655221,  0.02553546,  1.65660022,
        -1.40830397],
       [ 0.44457221, -0.02736982,  0.95841322,  1.22516897,  0.01824222,
         0.22981035],
       [-1.23893459,  1.10904233,  0.48262226, -0.25198918, -1.35439268,
        -1.6005458 ],
       [-1.24027352,  0.32829568,  0.13950629, -0.82236962, -0.78002692,
         0.2467246 ]])

In [9]:
from random import normalvariate
N = 100000
%timeit s1 = [normalvariate(0,1)for _ in range(N)] 

85.3 ms ± 984 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%timeit np.random.normal(size=N)

3.35 ms ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
