In [2]:
import numpy as np

In [3]:
arr1 = np.arange(20)

In [4]:
arr1[4]

4

In [5]:
arr1[4:10]

array([4, 5, 6, 7, 8, 9])

In [6]:
arr1[4:10] = 20

In [7]:
arr1

array([ 0,  1,  2,  3, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
'''
将一个标量值赋值给一个切片是，该值会自动传播到整个选区
与列表最重要数组切片时原始数据的视图，意味着数据不会被复制
'''
arr_s = arr1[4:10]
arr_s

array([20, 20, 20, 20, 20, 20])

In [10]:
arr_s[2] = 234

In [11]:
arr1

array([  0,   1,   2,   3,  20,  20, 234,  20,  20,  20,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [12]:
arr_s[:] = 20

In [13]:
arr1

array([ 0,  1,  2,  3, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr_s1 = arr1[4:10].copy()

In [16]:
arr_s1[:] = 234
arr_s1

array([234, 234, 234, 234, 234, 234])

In [17]:
arr1

array([ 0,  1,  2,  3, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])